GET http://localhost:3000/users
###
POST http://localhost:3000/users
content-type: application/json

{
    "user_name":"victor pawlek",
    "user_birthday" : "2003-02-08",
    "user_activitylevel":4
}
###
PATCH http://localhost:3000/users/6
content-type: application/json

{

    "user_activitylevel":3
}
###
DELETE http://localhost:3000/users/8
###


GET http://localhost:3000/plans
###
GET http://localhost:3000/gyms
###
GET http://localhost:3000/sessions
###
